-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Contacts Table
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  position text,
  department text,
  email text,
  phone text,
  company text,
  "group" text,
  is_vip boolean default false
);

-- Calendar Events Table
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  type text check (type in ('personal', 'team', 'company')),
  color text
);

-- Todos Table
create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  project text,
  due_date timestamp with time zone,
  status text check (status in ('대기', '진행중', '완료')) default '대기',
  priority text check (priority in ('상', '중', '하')) default '중',
  assignee text
);

-- Memos Table
create table memos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  date timestamp with time zone default timezone('utc'::text, now()),
  "group" text
);

-- Drive Files Table
create table drive_files (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text,
  size text,
  date timestamp with time zone default timezone('utc'::text, now()),
  owner text,
  is_starred boolean default false,
  path text -- Path in Supabase Storage
);

-- Mails Table
create table mails (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  folder text check (folder in ('inbox', 'sent', 'draft', 'trash', 'spam')) default 'inbox',
  sender text,
  sender_email text,
  title text,
  preview text,
  content text,
  date timestamp with time zone default timezone('utc'::text, now()),
  is_read boolean default false,
  tag text,
  has_attachment boolean default false,
  is_vip boolean default false,
  is_important boolean default false,
  is_mentioned boolean default false
);

-- Meeting Rooms Table
create table meeting_rooms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  capacity integer,
  location text,
  facilities text[],
  is_available boolean default true,
  next_available_time timestamp with time zone
);

-- Meetings Table
create table meetings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  room_id bigint references meeting_rooms(id),
  attendees text[]
);

-- Initial Data for Contacts (as per PRD)
insert into contacts (name, position, department, email, phone, company, "group", is_vip) values
('김태호', 'PM', '디지털혁신팀', 'th.kim@b2b.com', '010-1234-5678', 'ChungAng SDS', '팀원', true),
('남여원', '선임', '마케팅팀', 'yw.nam@b2b.com', '010-4567-8901', 'ChungAng SDS', '협력부서', false),
('연승민', '선임', '디지털혁신팀', 'sm.yeon@b2b.com', '010-2345-6789', 'ChungAng SDS', '팀원', false),
('강동훈', '수석', '디지털혁신팀', 'dh.kang@b2b.com', '010-3456-7890', 'ChungAng SDS', '협력부서', false),
('이민규', '사원', '디지털혁신팀', 'ms.lee@b2b.com', '010-5678-9012', 'ChungAng SDS', '팀원', false),
('민진호', '팀장', '영업1팀', 'jh.min@b2b.com', '010-6789-0123', 'ChungAng SDS', '임원', false),
('박혜민', '선임', 'DB운영팀', 'hm.park@b2b.com', '010-1111-2222', 'ChungAng SDS', '팀원', false),
('변영빈', '선임', '프론트엔드냠냠팀', 'yb.byun@b2b.com', '010-2222-3333', 'ChungAng SDS', '팀원', false),
('이그림', '수석', 'DB운영팀', 'gr.lee@b2b.com', '010-3333-4444', 'ChungAng SDS', '팀원', false),
('김순옥', '선임', '풀스택개발팀', 'so.kim@b2b.com', '010-4444-5555', 'ChungAng SDS', '팀원', false),
('이기성', '대표', '소프트웨어협력사', 'ks.lee@partner.com', '010-5555-6666', 'ChungAng SDS', '외부', true),
('조승현', '선임', '백엔드팀', 'sh.jo@b2b.com', '010-6666-7777', 'ChungAng SDS', '팀원', false),
('장영권', '선임', '디자인팀', 'yg.jang@b2b.com', '010-7777-8888', 'ChungAng SDS', '협력부서', false),
('유다경', '선임', '웹퍼블리싱팀', 'dk.yu@b2b.com', '010-8888-9999', 'ChungAng SDS', '팀원', false),
('유혜인', '수석고문', '건설자문부', 'hi.yu@construction.com', '010-9999-0001', 'ChungAng SDS', '외부', true),
('허예진', '사무관', '감사원파견', 'yj.heo@gov.kr', '010-0001-1112', 'ChungAng SDS', '외부', false),
('나금빈', '선임', '사내뷰티및퍼스널컬러컨설팅팀', 'gb.na@b2b.com', '010-1112-2223', 'ChungAng SDS', '팀원', false),
('이슬', '이사', '투자전략실', 'sl.lee@invest.com', '010-2223-3334', 'ChungAng SDS', '외부', true),
('최다영', '수석고문', '인공지능머신러닝개발팀', 'dy.choi@b2b.com', '010-3334-4445', 'ChungAng SDS', '외부', true);

-- Enable RLS (Row Level Security) - Optional for now but good practice
alter table contacts enable row level security;
alter table events enable row level security;
alter table todos enable row level security;
alter table memos enable row level security;
alter table drive_files enable row level security;
alter table mails enable row level security;
alter table meeting_rooms enable row level security;
alter table meetings enable row level security;

-- Create policies to allow all access for now (since we are using a single dev account)
-- In production, this should be restricted to authenticated users and their own data
create policy "Enable all access for all users" on contacts for all using (true) with check (true);
create policy "Enable all access for all users" on events for all using (true) with check (true);
create policy "Enable all access for all users" on todos for all using (true) with check (true);
create policy "Enable all access for all users" on memos for all using (true) with check (true);
create policy "Enable all access for all users" on drive_files for all using (true) with check (true);
create policy "Enable all access for all users" on mails for all using (true) with check (true);
create policy "Enable all access for all users" on meeting_rooms for all using (true) with check (true);
create policy "Enable all access for all users" on meetings for all using (true) with check (true);
