-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Contacts Table
create table contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  position text,
  department text,
  email text,
  phone text,
  company text,
  "group" text,
  is_vip boolean default false
);

-- Calendar Events Table
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  type text check (type in ('personal', 'team', 'company')),
  color text
);

-- Todos Table
create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  project text,
  due_date timestamp with time zone,
  status text check (status in ('대기', '진행중', '완료')) default '대기',
  priority text check (priority in ('상', '중', '하')) default '중',
  assignee text
);

-- Memos Table
create table memos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  date timestamp with time zone default timezone('utc'::text, now()),
  "group" text
);

-- Drive Files Table
create table drive_files (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text,
  size text,
  date timestamp with time zone default timezone('utc'::text, now()),
  owner text,
  is_starred boolean default false,
  path text -- Path in Supabase Storage
);

-- Mails Table
create table mails (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  folder text check (folder in ('inbox', 'sent', 'draft', 'trash', 'spam')) default 'inbox',
  sender text,
  sender_email text,
  title text,
  preview text,
  content text,
  date timestamp with time zone default timezone('utc'::text, now()),
  is_read boolean default false,
  tag text,
  has_attachment boolean default false,
  is_vip boolean default false,
  is_important boolean default false,
  is_mentioned boolean default false
);

-- Meeting Rooms Table
create table meeting_rooms (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  capacity integer,
  location text,
  facilities text[],
  is_available boolean default true,
  next_available_time timestamp with time zone
);

-- Meetings Table
create table meetings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  room_id bigint references meeting_rooms(id),
  attendees text[]
);

-- Initial Data for Contacts (as per PRD)
insert into contacts (name, position, department, email, phone, company, "group", is_vip) values
('김태호', 'PM', '디지털혁신팀', 'th.kim@b2b.com', '010-1234-5678', 'ChungAng SDS', '팀원', true),
('남여원', '선임', '마케팅팀', 'yw.nam@b2b.com', '010-4567-8901', 'ChungAng SDS', '협력부서', false),
('연승민', '선임', '디지털혁신팀', 'sm.yeon@b2b.com', '010-2345-6789', 'ChungAng SDS', '팀원', false),
('강동훈', '수석', '디지털혁신팀', 'dh.kang@b2b.com', '010-3456-7890', 'ChungAng SDS', '협력부서', false),
('이민규', '사원', '디지털혁신팀', 'ms.lee@b2b.com', '010-5678-9012', 'ChungAng SDS', '팀원', false),
('민진호', '팀장', '영업1팀', 'jh.min@b2b.com', '010-6789-0123', 'ChungAng SDS', '임원', false),
('박혜민', '선임', 'DB운영팀', 'hm.park@b2b.com', '010-1111-2222', 'ChungAng SDS', '팀원', false),
('변영빈', '선임', '프론트엔드냠냠팀', 'yb.byun@b2b.com', '010-2222-3333', 'ChungAng SDS', '팀원', false),
('이그림', '수석', 'DB운영팀', 'gr.lee@b2b.com', '010-3333-4444', 'ChungAng SDS', '팀원', false),
('김순옥', '선임', '풀스택개발팀', 'so.kim@b2b.com', '010-4444-5555', 'ChungAng SDS', '팀원', false),
('이기성', '대표', '소프트웨어협력사', 'ks.lee@partner.com', '010-5555-6666', 'ChungAng SDS', '외부', true),
('조승현', '선임', '백엔드팀', 'sh.jo@b2b.com', '010-6666-7777', 'ChungAng SDS', '팀원', false),
('장영권', '선임', '디자인팀', 'yg.jang@b2b.com', '010-7777-8888', 'ChungAng SDS', '협력부서', false),
('유다경', '선임', '웹퍼블리싱팀', 'dk.yu@b2b.com', '010-8888-9999', 'ChungAng SDS', '팀원', false),
('유혜인', '수석고문', '건설자문부', 'hi.yu@construction.com', '010-9999-0001', 'ChungAng SDS', '외부', true),
('허예진', '사무관', '감사원파견', 'yj.heo@gov.kr', '010-0001-1112', 'ChungAng SDS', '외부', false),
('나금빈', '선임', '사내뷰티및퍼스널컬러컨설팅팀', 'gb.na@b2b.com', '010-1112-2223', 'ChungAng SDS', '팀원', false),
('이슬', '이사', '투자전략실', 'sl.lee@invest.com', '010-2223-3334', 'ChungAng SDS', '외부', true),
('최다영', '수석고문', '인공지능머신러닝개발팀', 'dy.choi@b2b.com', '010-3334-4445', 'ChungAng SDS', '외부', true);

-- ========================================
-- Phase 1: 칸반 보드 테이블
-- ========================================

-- Projects Table (프로젝트 목록)
create table projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  status text check (status in ('active', 'completed', 'archived')) default 'active',
  color text default '#3b82f6'
);

-- Kanban Columns Table (칸반 컬럼)
create table kanban_columns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references projects(id) on delete cascade,
  name text not null,
  color text default '#6b7280',
  position integer not null default 0
);

-- Kanban Tasks Table (칸반 태스크)
create table kanban_tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  column_id bigint references kanban_columns(id) on delete cascade,
  title text not null,
  description text,
  assignee_id bigint references contacts(id),
  due_date timestamp with time zone,
  priority text check (priority in ('low', 'medium', 'high', 'urgent')) default 'medium',
  position integer not null default 0,
  tags text[],
  checklist jsonb default '[]'::jsonb
);

-- Task Comments Table (태스크 댓글)
create table task_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task_id bigint references kanban_tasks(id) on delete cascade,
  author_id bigint references contacts(id),
  content text not null
);

-- Activity Logs Table (활동 로그)
create table activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id bigint references contacts(id),
  action_type text not null,
  target_type text not null,
  target_id bigint,
  description text,
  metadata jsonb default '{}'::jsonb
);

-- ========================================
-- 칸반 시드 데이터
-- ========================================

-- 프로젝트 데이터
insert into projects (name, description, status, color) values
('웹 리뉴얼 프로젝트', '회사 공식 웹사이트 전면 리뉴얼', 'active', '#3b82f6'),
('모바일 앱 개발', 'iOS/Android 네이티브 앱 개발', 'active', '#8b5cf6'),
('ERP 시스템 구축', '전사 자원관리 시스템 구축', 'active', '#10b981'),
('AI 챗봇 도입', '고객 상담용 AI 챗봇 개발', 'active', '#f59e0b'),
('보안 인프라 강화', '사내 보안 시스템 업그레이드', 'completed', '#ef4444');

-- 칸반 컬럼 데이터 (프로젝트 1번)
insert into kanban_columns (project_id, name, color, position) values
(1, 'Backlog', '#6b7280', 0),
(1, 'To Do', '#3b82f6', 1),
(1, 'In Progress', '#f59e0b', 2),
(1, 'Review', '#8b5cf6', 3),
(1, 'Done', '#10b981', 4);

-- 칸반 컬럼 데이터 (프로젝트 2번)
insert into kanban_columns (project_id, name, color, position) values
(2, 'Backlog', '#6b7280', 0),
(2, 'To Do', '#3b82f6', 1),
(2, 'In Progress', '#f59e0b', 2),
(2, 'QA Testing', '#ef4444', 3),
(2, 'Done', '#10b981', 4);

-- 칸반 태스크 데이터 (프로젝트 1번의 컬럼들)
insert into kanban_tasks (column_id, title, description, assignee_id, due_date, priority, position, tags) values
-- Backlog (column_id = 1)
(1, 'SEO 최적화 전략 수립', '검색엔진 최적화를 위한 전략 문서 작성', 1, '2025-12-20', 'medium', 0, ARRAY['SEO', '마케팅']),
(1, '다국어 지원 검토', '영어/일본어/중국어 지원 범위 결정', 2, '2025-12-25', 'low', 1, ARRAY['국제화']),
-- To Do (column_id = 2)
(2, 'UI/UX 디자인 시안 검토', '디자인팀에서 전달받은 시안 피드백', 1, '2025-12-10', 'high', 0, ARRAY['디자인', '긴급']),
(2, '데이터베이스 스키마 설계', 'ERD 작성 및 테이블 구조 확정', 4, '2025-12-12', 'high', 1, ARRAY['백엔드', 'DB']),
(2, '프론트엔드 컴포넌트 설계', '재사용 가능한 UI 컴포넌트 구조 설계', 3, '2025-12-15', 'medium', 2, ARRAY['프론트엔드']),
-- In Progress (column_id = 3)
(3, '메인 페이지 개발', '히어로 섹션, 서비스 소개, CTA 영역 구현', 3, '2025-12-08', 'urgent', 0, ARRAY['프론트엔드', '개발']),
(3, 'API 엔드포인트 개발', 'RESTful API 설계 및 구현', 4, '2025-12-10', 'high', 1, ARRAY['백엔드', 'API']),
(3, '로그인/회원가입 구현', 'OAuth 및 이메일 인증 구현', 12, '2025-12-09', 'high', 2, ARRAY['인증', '보안']),
-- Review (column_id = 4)
(4, '반응형 레이아웃 QA', '모바일/태블릿 반응형 테스트', 8, '2025-12-06', 'medium', 0, ARRAY['QA', '반응형']),
(4, '성능 최적화 검토', '라이트하우스 점수 개선 작업 확인', 3, '2025-12-07', 'medium', 1, ARRAY['성능']),
-- Done (column_id = 5)
(5, '프로젝트 킥오프 미팅', '이해관계자 미팅 및 요구사항 확정', 1, '2025-11-20', 'high', 0, ARRAY['미팅']),
(5, '기술 스택 선정', 'React, TypeScript, Tailwind 등 기술 스택 확정', 4, '2025-11-25', 'high', 1, ARRAY['기획']),
(5, '개발 환경 세팅', 'CI/CD 파이프라인 및 개발 환경 구축', 12, '2025-11-28', 'medium', 2, ARRAY['DevOps']);

-- Enable RLS (Row Level Security) - Optional for now but good practice
alter table contacts enable row level security;
alter table events enable row level security;
alter table todos enable row level security;
alter table memos enable row level security;
alter table drive_files enable row level security;
alter table mails enable row level security;
alter table meeting_rooms enable row level security;
alter table meetings enable row level security;

-- Create policies to allow all access for now (since we are using a single dev account)
-- In production, this should be restricted to authenticated users and their own data
create policy "Enable all access for all users" on contacts for all using (true) with check (true);
create policy "Enable all access for all users" on events for all using (true) with check (true);
create policy "Enable all access for all users" on todos for all using (true) with check (true);
create policy "Enable all access for all users" on memos for all using (true) with check (true);
create policy "Enable all access for all users" on drive_files for all using (true) with check (true);
create policy "Enable all access for all users" on mails for all using (true) with check (true);
create policy "Enable all access for all users" on meeting_rooms for all using (true) with check (true);
create policy "Enable all access for all users" on meetings for all using (true) with check (true);

-- 칸반 테이블 RLS
alter table projects enable row level security;
alter table kanban_columns enable row level security;
alter table kanban_tasks enable row level security;
alter table task_comments enable row level security;
alter table activity_logs enable row level security;

create policy "Enable all access for all users" on projects for all using (true) with check (true);
create policy "Enable all access for all users" on kanban_columns for all using (true) with check (true);
create policy "Enable all access for all users" on kanban_tasks for all using (true) with check (true);
create policy "Enable all access for all users" on task_comments for all using (true) with check (true);
create policy "Enable all access for all users" on activity_logs for all using (true) with check (true);
